[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "paneltime_mp"
version = "1.0.1"
description = "Multiprocessing interface"
readme = "README.md"
requires-python = ">=3.8"
license = "GPL-3.0-only"

authors = [
  { name = "Espen Sirnes", email = "espen.sirnes@uit.no" }
]

keywords = ["econometrics"]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python :: 3.8"
]

[project.urls]
Homepage = "https://github.com/espensirnes/paneltime_mp"

[project.optional-dependencies]
linux = ["gcc"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = ["*.tests", "*.tests.*", "*.test.*", "*__pycache__*"]
